Importing environment from .env file
THIS APP IS IN DEBUG MODE.                 YOU SHOULD NOT SEE THIS IN PRODUCTION.
Flask Base Â∫îÁî®ÊúçÂä°Âô®ÂêØÂä®‰∏≠...
ÊúçÂä°Âô®Âú∞ÂùÄ: http://127.0.0.1:5000
Ë∞ÉËØïÊ®°Âºè: True
Êï∞ÊçÆÂ∫ì: sqlite:////root/projects/flask-base/data-dev.sqlite
--------------------------------------------------
Ê≠£Âú®ÂàùÂßãÂåñÊï∞ÊçÆÂ∫ì...
Êï∞ÊçÆÂ∫ìÂàùÂßãÂåñÂÆåÊàêÔºÅ
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [19/Sep/2025 16:05:33] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:05:38] "[37mGET /account/login HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:05:50] "[32mGET /admin HTTP/1.1[0m" 308 -
127.0.0.1 - - [19/Sep/2025 16:07:05] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:07:05] "[37mGET /static/styles/app.css?fdfc7b77 HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:07:05] "[37mGET /static/webassets-external/6dcb662747c95b962b2f67be290b20aa_jquery.min.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:07:05] "[37mGET /static/webassets-external/51d88757e693216a6fb8cefca585527c_tablesort.min.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:07:05] "[37mGET /static/webassets-external/eef7346eec8478be3d80a8137ae462a9_semantic.min.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:07:05] "[37mGET /static/webassets-external/10f3f68a2a85e84d91b965af2bd9af33_semantic.min.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:07:05] "[37mGET /static/webassets-external/c8e5d6b9e4ea359d0622ff85e0a61fa9_zxcvbn.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:07:05] "[37mGET /static/webassets-external/1101724d96626d6bdae557db01e4a395_app.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:07:06] "[37mGET /static/fonts/vendor/semantic/icons.woff2 HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:07:19] "[37mGET /account/register HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:08:06] "[32mGET /admin HTTP/1.1[0m" 308 -
127.0.0.1 - - [19/Sep/2025 16:08:06] "[32mGET /admin/ HTTP/1.1[0m" 302 -
127.0.0.1 - - [19/Sep/2025 16:08:06] "[37mGET /account/login?next=%2Fadmin%2F HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:08:06] "[37mGET /static/webassets-external/eef7346eec8478be3d80a8137ae462a9_semantic.min.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:08:06] "[37mGET /static/webassets-external/6dcb662747c95b962b2f67be290b20aa_jquery.min.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:08:06] "[37mGET /static/styles/app.css?fdfc7b77 HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:08:06] "[37mGET /static/webassets-external/51d88757e693216a6fb8cefca585527c_tablesort.min.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:08:06] "[37mGET /static/webassets-external/10f3f68a2a85e84d91b965af2bd9af33_semantic.min.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:08:06] "[37mGET /static/webassets-external/c8e5d6b9e4ea359d0622ff85e0a61fa9_zxcvbn.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:08:06] "[37mGET /static/webassets-external/1101724d96626d6bdae557db01e4a395_app.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:08:06] "[36mGET /static/fonts/vendor/semantic/icons.woff2 HTTP/1.1[0m" 304 -
127.0.0.1 - - [19/Sep/2025 16:12:30] "[37mGET /account/login HTTP/1.1[0m" 200 -
[2025-09-19 16:12:36,771] ERROR in app: Exception on /account/login [POST]
Traceback (most recent call last):
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/wtforms/validators.py", line 401, in __call__
    import email_validator
ModuleNotFoundError: No module named 'email_validator'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/app/account/views.py", line 45, in login
    if form.validate_on_submit():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/wtforms/form.py", line 330, in validate
    return super().validate(extra)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/wtforms/form.py", line 147, in validate
    if not field.validate(self, extra):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/wtforms/fields/core.py", line 234, in validate
    stop_validation = self._run_validation_chain(form, chain)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/wtforms/fields/core.py", line 254, in _run_validation_chain
    validator(form, self)
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/wtforms/validators.py", line 403, in __call__
    raise Exception(
Exception: Install 'email_validator' for email validation support.
127.0.0.1 - - [19/Sep/2025 16:12:36] "[35m[1mPOST /account/login HTTP/1.1[0m" 500 -
127.0.0.1 - - [19/Sep/2025 16:14:37] "[31m[1mPOST /account/login HTTP/1.1[0m" 400 -
127.0.0.1 - - [19/Sep/2025 16:14:45] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:14:45] "[37mGET /static/webassets-external/eef7346eec8478be3d80a8137ae462a9_semantic.min.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:14:45] "[37mGET /static/styles/app.css?fdfc7b77 HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:14:50] "[37mGET /account/login HTTP/1.1[0m" 200 -
[2025-09-19 16:14:56,033] ERROR in app: Exception on /account/login [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.12/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_hashlib.UnsupportedDigestmodError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/app/account/views.py", line 48, in login
    user.verify_password(form.password.data):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/app/models/user.py", line 86, in verify_password
    return check_password_hash(self.password_hash, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/werkzeug/security.py", line 221, in check_password_hash
    return safe_str_cmp(_hash_internal(method, salt, password)[0], hashval)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/werkzeug/security.py", line 157, in _hash_internal
    mac = _create_mac(salt, password, method)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/werkzeug/security.py", line 174, in _create_mac
    return hmac.HMAC(key, msg, hashfunc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/hmac.py", line 64, in __init__
    self._init_old(key, msg, digestmod)
  File "/usr/lib/python3.12/hmac.py", line 80, in _init_old
    self._outer = digest_cons()
                  ^^^^^^^^^^^^^
  File "/root/projects/flask-base/venv/lib/python3.12/site-packages/werkzeug/security.py", line 169, in hashfunc
    return hashlib.new(method, d)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type scrypt:32768:8:1
127.0.0.1 - - [19/Sep/2025 16:14:56] "[35m[1mPOST /account/login HTTP/1.1[0m" 500 -
127.0.0.1 - - [19/Sep/2025 16:15:19] "[37mGET /account/login HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:15:19] "[31m[1mPOST /account/login HTTP/1.1[0m" 400 -
127.0.0.1 - - [19/Sep/2025 16:15:19] "[37mGET /account/register HTTP/1.1[0m" 200 -
127.0.0.1 - - [19/Sep/2025 16:15:19] "[37mGET / HTTP/1.1[0m" 200 -
